let pdata = {
    "TEAMAKER'S GUESTHOUSE" : {
        "메인사진" : "teamakers_start",
        "제목" : "teamakers",
		"작은사진" : "teamakers_small",
		"작은사진텍스트" : "Our entry to the Teamakers Guest House competition received<br>an honourable mention in this open international competition.<br><br>A considered approach has been taken to design a building that<br>sits comfortably in the current context. Careful attention has<br>been paid to the material choices to reflect the function of the<br>building while being aesthetically distinct and proudly represent<br>the Lauku Tea brand and your continued narrative.<br><br><br>We have thoughtfully composed a building that opens up to<br>nature so that guests can experience more of their surroundings<br>while they work.<br>",
		"큰사진" : "teamakers_big",
		"중간사진" : "teamakers_half",
		"중간사진텍스트" : "The spaces allows for two intertwining journeys to occur as the tea maker<br> meanders from the outdoors to the<br>indoors, from production to accommodation. Central to<br>our design is the drying chimney. Used as a highly<br>controlled drying space, this drying chimney is<br>constructed from recycled stone with an added pink dye<br>to create a warm to touch, terrazzo style chimney space<br>reminiscent to the speckled patterns of tea leaves<br>",
		"배경색박스텍스트" : "Our design is a distillation of the process<br>of herbal tea production, the Latvian wilderness,<br>and traditional rural Latvian building typologies<br>where the hearth was the focal point of shelters.",
		"배경색박스배경색" : "red",
		"마지막사진" : "teamakers_last",
		"다음프로젝트명" : "N1C",
		"다음프로젝트메인사진" : "teamakers_next"
    },
    "N1C" : {
        "메인사진" : "n1c_start",
        "제목" : "N1C",
		"작은사진" : "n1c_small",
		"작은사진텍스트" : "The N1C centre is the new home for the Somalian Youth<br>Development Resource Centre (SYDRC) and the Dragon Hall<br>Trust who are both charities providing education and activities at<br>and from the new community building.",
		"큰사진" : "n1c_big",
		"중간사진" : "n1c_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "n1c_last",
		"다음프로젝트명" : "ST DIONIS ROAD",
		"다음프로젝트메인사진" : "n1c_next"
    },
    "ST DIONIS ROAD" : {
        "메인사진" : "stdionis_start",
        "제목" : "ST DIONIS ROAD",
		"작은사진" : "stdionis_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "stdionis_big",
		"중간사진" : "stdionis_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "stdionis_last",
		"다음프로젝트명" : "COLOURED CONCRETE HOUSE",
		"다음프로젝트메인사진" : "stdionis_next"
    },
    "COLOURED CONCRETE HOUSE" : {
        "메인사진" : "coloured_start",
        "제목" : "COLOURED CONCRETE HOUSE",
		"작은사진" : "coloured_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "coloured_big",
		"중간사진" : "coloured_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "coloured_last",
		"다음프로젝트명" : "WHYTELEAFE HILL",
		"다음프로젝트메인사진" : "coloured_next"
    },
    "WHYTELEAFE HILL" : {
        "메인사진" : "whyteleafe_start",
        "제목" : "WHYTELEAFE HILL",
		"작은사진" : "whyteleafe_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "whyteleafe_big",
		"중간사진" : "whyteleafe_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "whyteleafe_last",
		"다음프로젝트명" : "MANOR ROAD",
		"다음프로젝트메인사진" : "whyteleafe_next"
    },
    "MANOR ROAD" : {
        "메인사진" : "manorroad_start",
        "제목" : "MANOR ROAD",
		"작은사진" : "manorroad_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "manorroad_big",
		"중간사진" : "manorroad_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "manorroad_last",
		"다음프로젝트명" : "THE MEADOWS",
		"다음프로젝트메인사진" : "manorroad_next"
    },
    "THE MEADOWS" : {
        "메인사진" : "themeadows_start",
        "제목" : "THE MEADOWS",
		"작은사진" : "themeadows_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "themeadows_big",
		"중간사진" : "themeadows_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "themeadows_last",
		"다음프로젝트명" : "CAMBRIDGE ROAD",
		"다음프로젝트메인사진" : "themeadows_next"
    },
    "CAMBRIDGE ROAD" : {
        "메인사진" : "cambridgeroad_start",
        "제목" : "CAMBRIDGE ROAD",
		"작은사진" : "cambridgeroad_small",
		"작은사진텍스트" : "어쩌구저쩌구",
		"큰사진" : "cambridgeroad_big",
		"중간사진" : "cambridgeroad_half",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"마지막사진" : "cambridgeroad_last",
		"다음프로젝트명" : "마지막 프로젝트 입니다.",
		"다음프로젝트메인사진" : "cambridgeroad_next"
    },
};

export default pdata;