let pdata = [
    {
		"eg" : "teamakers",
		"id" : 0,
		"타이틀" : "TEAMAKER'S^GUESTHOUSE",
        "제목" : "TEAMAKER",
		"작은사진텍스트" : "Our entry to the Teamakers Guest House competition received<br>an honourable mention in this open international competition.<br><br>A considered approach has been taken to design a building that<br>sits comfortably in the current context. Careful attention has<br>been paid to the material choices to reflect the function of the<br>building while being aesthetically distinct and proudly represent<br>the Lauku Tea brand and your continued narrative.<br><br><br>We have thoughtfully composed a building that opens up to<br>nature so that guests can experience more of their surroundings<br>while they work.<br>",
		"중간사진텍스트" : "The spaces allows for two intertwining journeys to occur as the tea maker<br> meanders from the outdoors to the<br>indoors, from production to accommodation. Central to<br>our design is the drying chimney. Used as a highly<br>controlled drying space, this drying chimney is<br>constructed from recycled stone with an added pink dye<br>to create a warm to touch, terrazzo style chimney space<br>reminiscent to the speckled patterns of tea leaves<br>",
		"배경색박스텍스트" : "Our design is a distillation of the process<br>of herbal tea production, the Latvian wilderness,<br>and traditional rural Latvian building typologies<br>where the hearth was the focal point of shelters.",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "N1C",
    },
    {
		"eg" : "n1c",
		"id" : 1,
		"타이틀" : "N1C",
		"작은사진텍스트" : "The N1C centre is the new home for the Somalian Youth<br>Development Resource Centre (SYDRC) and the Dragon Hall<br>Trust who are both charities providing education and activities at<br>and from the new community building.",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
    },
    {
		"eg" : "stdionisroad",
		"id" : 2,
		"타이틀" : "ST^DIONIS^ROAD",
        "제목" : "ST DIONIS ROAD",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "COLOURED CONCRETE HOUSE",
    },
    {
		"eg" : "colouredconcretehouse",
		"id" : 3,
		"타이틀" : "COLOURED^CONCRETE^HOUSE",
		"제목" : "WHYTELEAFE HILL",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "WHYTELEAFE HILL"
	},
    {
		"eg" : "whyteleafehill",
		"id" : 4,
		"타이틀" : "WHYTELEAFE^HILL",
        "제목" : "WHYTELEAFE HILL",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "MANOR ROAD",
    },
    {
		"eg" : "manororad",
		"id" : 5,
		"타이틀" : "MANOR^ROAD",
        "제목" : "MANOR ROAD",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "THE MEADOWS",
    },
    {
		"eg" : "themeadows",
		"id" : 6,
		"타이틀" : "THE^MEADOWS",
        "제목" : "THE MEADOWS",
		"작은사진텍스트" : 0,
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "CAMBRIDGE ROAD",
    },
    {
		"eg" : "embankment",
		"id" : 7,
		"타이틀" : "EMBANKMENT",
        "제목" : "CAMBRIDGE ROAD",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "NIGHTINGALE.",
    },
    {
		"eg" : "nightingale",
		"id" : 8,
		"타이틀" : "NIGHTINGALE",
        "제목" : "NIGHTINGALE",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "SWISSLAND HILL.",
    },
    {
		"eg" : "swisslandhill",
		"id" : 9,
		"타이틀" : "SWISSLAND^HILL",
        "제목" : "SWISSLAND HILL",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "WESTHUMBLE",
    },
    {
		"eg" : "westhumble",
		"id" : 10,
		"타이틀" : "WESTHUMBLE",
        "제목" : "WESTHUMBLE",
		"작은사진텍스트" : "어쩌구저쩌구",
		"중간사진텍스트" : "어쩌구저쩌구텍스트",
		"배경색박스텍스트" : "어저구저쩌구",
		"배경색박스배경색" : "red",
		"다음프로젝트명" : "TEAMAKER",
    },
];

export default pdata;